export {default as Course} from "./course/Course"
export {default as CTA} from "./cta/CTA"
export {default as Facilities } from "./facilities/Facilties"
export {default as Footer} from "./footer/Footer"
export {default as HContent} from "./hContent/HContent"
export {default as Navbar} from "./navbar/Navbar"
export {default as Button} from "./button/Button"